//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwentiethDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctors()
        {
            this.Visits = new HashSet<Visits>();
        }
    
        public int ID { get; set; }
        public string LastName { get; set; }
        public string Firstname { get; set; }
        public string Patronymic { get; set; }
        public int Room { get; set; }
        public string University { get; set; }
        public int TypeID { get; set; }
        public int Expperience { get; set; }
        public string Phone { get; set; }
        public int Born { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual DoctorTypes DoctorTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
