//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwentiethDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public int ID { get; set; }
        public int PatientID { get; set; }
        public int DoctorID { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public decimal Cost { get; set; }
        public int ExemptID { get; set; }
        public decimal Summa { get; set; }
        public string Comment { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Exempts Exempts { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
